import {Injectable} from '@angular/core';
import {EventConfiguration, StaffPerson, Wcif} from './classes';
import {saveAs} from 'file-saver';
import {getEventName, Person} from '@wca/helpers';
import * as moment from 'moment-timezone';
import {Helpers} from './helpers';

declare var pdfMake: any;

@Injectable({
  providedIn: 'root'
})
export class ExportService {

  private formats = [
    {id: 'a', label: 'ao5'},
    {id: 'm', label: 'mo3'},
    {id: '1', label: 'mo3'},
    {id: '2', label: 'mo3'},
    {id: '3', label: 'mo3'}
  ];

  constructor() {}

  csvGroupAndTaskAssignments(wcif: Wcif) {
    let csv: string = 'Name,' + wcif.events.map(event => event.id).join(',') + '\r\n';
    wcif.persons.forEach(p => {
      csv += (p.name + ',');
      csv += wcif.events.map(event => p[event.id].group).join(',');
      csv += '\r\n';
    });

    const filename = 'groupAndTaskAssignments-' + wcif.id + '.csv';
    this.downloadFile(csv, filename);
  }

  csvGroups(wcif: Wcif) {
    let csv: string = 'Name,' + wcif.events.map(event => event.id).join(',') + ',\r\n';
    wcif.persons.forEach(p => {
      csv += (p.name + ',');
      csv += wcif.events.map(event => p[event.id].group.split(';')[0]).join(',');
      csv += ',\r\n';
    });

    const filename = 'groups-' + wcif.id + '.csv';
    this.downloadFile(csv, filename);
  }

  csvEvents(wcif: Wcif) {
    let csv = 'event,label,format,limit,cumulative,cutoff,\r\n';
    wcif.events.forEach(e => {
      const label = getEventName(e.id);
      const format = this.formats.filter(f => f.id === e.round1.format)[0].label;
      const limit: string = ! e.round1.timeLimit ? '' : ExportService.centisToMinutesAndSeconds(e.round1.timeLimit.centiseconds);
      const cumulative: boolean = !! e.round1.timeLimit && e.round1.timeLimit.cumulativeRoundIds.length;
      const cutoff: string = ! e.round1.cutoff ? '' : ExportService.centisToMinutesAndSeconds(e.round1.cutoff.attemptResult);

      csv += (e.id + ',');
      csv += (label + ',');
      csv += (format + ',');
      csv += (limit + ',');
      csv += ((cumulative ? 'yes' : 'no') + ',');
      csv += (cutoff + ',');
      csv += '\r\n';
    });

    const filename = 'events-' + wcif.id + '.csv';
    this.downloadFile(csv, filename);
  }

  private static centisToMinutesAndSeconds(centiseconds) {
    if (! centiseconds) {
      return '';
    }
    const minutes = Math.floor(centiseconds / 6000);
    const seconds = Math.floor((centiseconds % 6000) / 100);
    return minutes + ':' + (seconds < 10 ? '0' : '') + seconds + (centiseconds % 100 === 0 ? '' : ('.' + centiseconds % 100));
  }

  pdfGroupOverview(wcif: Wcif) {
    const document = {
      content: [
      ],
      styles: {
      },
      defaultStyle: {
        fontSize: 11,
      },
      footer: {
        columns: [
          '',
          {
            alignment: 'right',
            text: 'Generated by AGE'
          }
        ],
        margin: [30, 0]
      }
    };

    wcif.events.forEach(event => {
      const configuration: EventConfiguration = event.configuration;
      if (configuration.skip) {
        return;
      }
      const groups: number = configuration.scrambleGroups * configuration.stages;
      for (let i = 1; i <= groups; i++) {
        // For every group, collect all competitors, judges, scramblers and runners
        const competitors = wcif.persons.filter(p => p[event.id].group.split(';')[0] === ('' + i));
        const judges = wcif.persons.filter(p => p[event.id].group.split(';').includes('J' + i));
        const scramblers = wcif.persons.filter(p => p[event.id].group.split(';').includes('S' + i));
        const runners = wcif.persons.filter(p => p[event.id].group.split(';').includes('R' + i));

        // Write information to pdf
        const headerLine: string = ' - group ' + i +  ' has ' + competitors.length + ' competitors, ' + judges.length + ' judges, '
            + scramblers.length + ' scramblers and ' + runners.length + ' runners\n';
        document.content.push(
          {
            text: [
              {text: event.id, bold: true},
              {text: headerLine},
              {text: '• Competitors: '},
              {text: competitors.map(p => p.name).join(', ') + '\n'},
              {text: '• Judges: '},
              {text: judges.map(p => p.name).join(', ') + '\n'},
              {text: '• Scramblers: '},
              {text: scramblers.map(p => p.name).join(', ') + '\n'},
              {text: '• Runners: '},
              {text: runners.map(p => p.name).join(', ') + '\n' + '\n'}
            ],
            unbreakable: true
          }
        );
      }
      document.content.push('\n\n');
    });

    const filename = 'namesPerGroupOverview-' + wcif.id + '.pdf';
    pdfMake.createPdf(document).download(filename);
  }

  pdfTableGroupAndTaskAssignments(wcif: Wcif) {
    const document = {
      pageOrientation: 'landscape',
      content: [
        {
          style: 'tableOverview',
          table: {
            headerRows: 1,
            paddingLeft: function(i, node) { return 0; },
            paddingRight: function(i, node) { return 0; },
            paddingTop: function(i, node) { return 2; },
            paddingBottom: function(i, node) { return 2; },
            body: []
          },
          layout: 'lightHorizontalLines'
        },
      ],
      styles: {
        tableOverview: {
          lineHeight: 0.7
        }
      },
      defaultStyle: {
        fontSize: 9,
      },
      footer: {
        columns: [
          '',
          {
            alignment: 'right',
            text: 'Generated by AGE'
          }
        ],
        margin: [30, 0]
      }
    };

    document.content[0].table.body.push(['Name']);
    wcif.events.forEach(event => {
      document.content[0].table.body[0].push(event.id);
    });
    wcif.persons.forEach(p => {
      const array = [p.name];
      wcif.events.forEach(event => {
        array.push(p[event.id].group);
      });
      document.content[0].table.body.push(array);
    });

    const filename = 'tableOverview-' + wcif.id + '.pdf';
    pdfMake.createPdf(document).download(filename);
  }

  pdfPersonalSchedules(wcif: Wcif, bordersOnNametags: boolean) {
    const document = {
      content: [
      ],
      styles: {
        nametag: {
          margin: [0, 30, 0, 0],
          lineHeight: 0.7
        },
        firstNametag: {
          margin: [0, 0, 0, 0],
          lineHeight: 0.7
        },
        tableExample: {
          margin: [0, 0, 0, 0],
          lineHeight: 0.7
        },
        name: {
          fontSize: 18,
          alignment: 'center',
          margin: [0, 10, 0, 0] // add white to top
        },
        wcaId: {
          fontSize: 10,
          alignment: 'center',
          margin: [0, 2, 0, 0] // add white to top
        },
        country: {
          fontSize: 10,
          alignment: 'center',
          margin: [0, 2, 0, 0] // add white to top
        },
        startTime: {
          fontSize: 7
        }
      },
      defaultStyle: {
        fontSize: 10,
      }
    };

    wcif.persons.forEach(p => {
      const nametag = this.getOneNametagToFill(bordersOnNametags);

      // Set name, wcaId and country on nametag
      nametag.table.body[0][1].table.body[0][0].text = p.name;
      nametag.table.body[0][1].table.body[1][0].text = 'Competitor id: ' + p.registrantId;
      nametag.table.body[0][1].table.body[2][0].text = ! p.wcaId ? ' ' : p.wcaId;
      nametag.table.body[0][1].table.body[3][0].text = this.getCountryName(p.countryIso2);

      // Add all events + group
      let i = 0;
      let j = 0;
      wcif.events.forEach(event => {
        if (p[event.id].group !== '') {
          nametag.table.body[0][0].table.body[0][i].table.body[j][0].text = this.formatStartTimeOf(event, wcif.schedule.venues[0].timezone);
          nametag.table.body[0][0].table.body[0][i].table.body[j][1] = this.getIconOf(event.id, 10);
          nametag.table.body[0][0].table.body[0][i].table.body[j][2] = p[event.id].group;

          j++;
          if (j > 5) {
            i++;
            j = 0;
          }
        }
      });

      // Cleanup empty space of personal schedule
      if (j === 0) { i--; }
      while (i < 2) {
        nametag.table.body[0][0].table.body[0].pop();
        i++;
      }

      // Add to nametags
      document.content.push(nametag);
    });

    document.content[0].style = 'firstNametag';

    const filename = 'personalSchedules-' + wcif.id + '.pdf';
    pdfMake.createPdf(document).download(filename);
  }

  private formatStartTimeOf(event, timezone: string): string {
    return moment(event.startTime).tz(timezone).format('H:mm');
  }

  private getOneNametagToFill(bordersOnNametags: boolean): any {
    return {
      style: 'nametag',
      table: {
        widths: [ 245, 245 ],
        body: [
          [
            {
              style: 'tableExample',
              table: {
                body: [
                  [
                    {
                      style: 'tableExample',
                      table: {
                        body: [
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' ']
                        ]
                      },
                      layout: 'noBorders'
                    }
                    ,
                    {
                      style: 'tableExample',
                      table: {
                        body: [
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' ']
                        ]
                      },
                      layout: 'noBorders'
                    }
                    ,
                    {
                      style: 'tableExample',
                      table: {
                        body: [
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' '],
                          [{ style: 'startTime', text: ' ' }, ' ', ' ']
                        ]
                      },
                      layout: 'noBorders'
                    }
                  ]
                ]
              },
              // layout: 'noBorders' // To disable borders around personal schedule
            }
            ,
            {
              style: 'tableExample',
              table: {
                widths: [ 240 ],
                body: [
                  [{
                    style: 'name',
                    text: ''
                  }],
                  [{
                    style: 'wcaId',
                    text: ''
                  }],
                  [{
                    style: 'wcaId',
                    text: ''
                  }],
                  [{
                    style: 'country',
                    text: ''
                  }],
                ]
              },
              layout: 'noBorders',
              alignment: 'center'
            }
          ]
        ]
      },
      layout: ( bordersOnNametags ? { hLineColor: 'lightgray', vLineColor: 'lightgray' } : 'noBorders' ),
      unbreakable: true
    };
  }

  private getIconOf(eventId: string, width: number): any {
    return {
      image: this.getDataUrlOf(eventId),
      width: width
    };
  }

  private getDataUrlOf(eventId: string): string {
    switch (eventId) {
      case '222' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAA5CAIAAADoTa/RAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACYSURBVGhD7di9DYAgEEBhdAamYP+eLZiCBegkEaO14RWXvK/xJ5G84hrvGGOkOM51DSJY7jsMvffW2n3/Qykl57weHvvPnLm3Wut69cv8fB30sf1MZ5dkLslckrkkc0nmkswlmUsylxQsN9ivpWsRkrkkc0nuyD7ckYViLslckrkkc0nmkswlmUsylxQs1x0ZydklhcpN6QK9V6hxrd/f5AAAAABJRU5ErkJggg==';
      case '333' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD0AAAA+CAIAAAAXlIQQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF2SURBVGhD7Zcxq4JQGIbPvaAu4uQUiXstbU6N/YDWdv9XU6s/ocHJzcVwDxpCJMLFIrjn6gddSLz3VrwgvM9g5/vq9D3DEc77Ude1GiCf8jk06I3lfr71Ik3TsizzPL/dbm2zE8/zlsulaZpSK5UkSRzHeqGb0+nUMIy2/8hkMnFdV4pXhuqdLYfDYbFYSLeXMAxPp5Nsa1iv1/Ldb2y3W9nT8PRQnm8s9MZCbyz0xkJvLPTGcr8PVlW12WzO53Nb9vDG++DTQ5nTsNAby1C97zlNpyCdhaTbi05WOl/Jtoa/5zT9S9nT8PRQnhMs9MZCbyz0xkJvLPTGMlRv5jQs9MYy/PfycrlEUbTf79uyB8dxVquVbdtSK3U8HvM8v16vWZbp/5FuF/P5PAgCKV4Z2qS1b5gvEdAbC72x0BsLvbHQG8t7vH3flxWK7vvgeDwejUZt/xHLsmazmX5KrVRRFLvdTooHft4Te+6D/xrKfImF3kiU+gLRNElegZlJdwAAAABJRU5ErkJggg==';
      case '444' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD0AAAA9CAIAAACRAPa+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHNSURBVGhD7ZpPqwFhFIdndMVCoiY7VrKgJJ+BxWRjbW/jM5gslHwEG2VtQ/kAFlZSFmwVUcpO2RilHPecG9130u3WnHrrPAvze//UPDSaX82YrusaGhKgo27Q773ZbMbjMU6pRKPRWq0WiUQg32630Wh0OBxwSSWXy9m2jflyuaxWq/v9jkOVbDZrWRbm/X6/2+0wq4RCoUKhAJ80Bm9gOp3S2ItyuXw8HnHn+Xyu1+u04EWr1cKdwHq9zufztOAFnJe2uu5gMKBZL94dAF2vE/HmRbx5EW9edPX+wkM4HC6VSphVkslkIEDf0DRNuMN92ByLxSj5ifQqXsSbl1eP7ff70Dlx9hepVKrT6cTjccjX67Xb7S4WC1xSqVQqjUYD8+l0Gg6HH/5C1Wo1nU5jns/ns9kMs8p7l37yLIXSY9kQb17Emxfx5kVXb397bDAYzGQyiUSCxgpwXkqGAffCPzoA0mN5EW9e6PpeLpeO4+CUyr977Ha7bTabUCFxqNJut4vFIubJZNLr9TCrvDs8+W6F0mO5EG9exJsX8eZFV2/psbzI9c2Lrt7SY3+QHvsJ8eZFvHkRb1509X49v/TjPTz/nl9Kj+VFT2/DeACjuLGYHiC5wwAAAABJRU5ErkJggg==';
      case '555' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAA7CAIAAAClhQ7aAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJCSURBVGhD7Zk7rylRFMfH+xGPiQiJRIKCRiQKUem0Co1KdBIfQaEk8RGUao1Cq1OJDg2NQiKRiAji/biLtWfuOcdJbjP7JpOsXyL+s/bes/6RbdZeaM7ns6AetOxdJbw+3dPpVK/XB4MBi0mUSqVMJoO60+k0Gg3UMolEolwum81m0LPZrFKpbDYbHEJEUaxWq8FgELQiWfTwej6fq9Wq2+2+R/+Sz+eZEoT9fv85AXzAWtTX63U6nQ6HQ7xEYrEYxFErkkVlm4Hs8oTs8uT1ZNDpdKlUKhAIYEgmFAox9da1Wo1dSPj9fliL2ul0FgqFH0XHZDJBHLUiWaiq8URldl+bAWrGdru93W4sJmG1Wi0WC+rj8Xg4HFDL6PV6h8Oh0WhAw/Ldbvd4PHAI0Wq1drsdpoFWJIsAdqHQF4vF99A3ms0mjCKgWfQLsArW4oTRaAQllw1IQATiOEGRLLR3eUJ2eUJ2eUJFmCdklyevvXu5XNrt9nw+ZzEJOJ4mk0nU/X6/1+uhloGTaDabNRqNoJfLZavV+vFNgPNuLpfzer2gFclCZwaekF2ekF2e/NK43+/38Xi8Xq9tNhtGANDpdNrn80UiERb63lIbDIZwOAw3icfj7KHzr8Z9MpksFovPLC6XKxqNynemxv1/QXa5AnuXijAvyC5PyC5PVGZXZT+Y0pmBJyrcu9S4M+jMoCrILk9UZvdVHqG+ud1u6JgxJPPZUrMLCVjF/kyUGnePx4OXiCiKEEetSBYqwjxRlV1B+AO3RUehTqSdcgAAAABJRU5ErkJggg==';
      case '666' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADsAAAA8CAIAAABXQlVcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAMiSURBVGhD7ZlNSzJRFMfV7E18KRAXQWIgGgliQqu2thAJ+gBtA+kTiCkuFPETiEu/Q9vApQtBRMVFm8JEWkhZiaVWPv+Ze8cnJhhq6CoD9wfdzvyPZ+akx3vu7epHo5FOUxjob+0gvMfVajWZTFJBIp1OB4PBt7e3XC5XqVSoKuJ0OrPZ7Obm5s3NTSKR6Pf71CESjUaPj49hXF5eFgoFIhI2NjYymczOzs7j42M8Hm+329QhEolEzs/PYSgEwjbiB2ldXV2Jrv9cXFxgnE6nvV5P5j06Ovr8/IQxmUyur6/r9TrRCaenp8QYDAayQL/fjxAYCL+7u5N5Dw8PiaEQCLRXFTxj9qjJ2OFwrKys0Iu5oyZjk8lkNApf2YXAOwh7tJexDlVRKpXoxRcgwoV+dnZ2RiUJdJButwtvo9HA3E5ViWKxCBeAQSUJvBghcCEcN6GqRCqVIoEK+QBeFezhGbNHexkLrWttbS0UCpHrGRAx6vV6u90u825vbxsMwp+6vLzs8XjQtIlOMJvNM0MWiGUuQmAgHDf57iWGQj6A9zz2CO/xeDx+eXmhgoTFYsECDXuQ5+fn9/d3qopgGWS1WlEw0BFI9iMzsE5aX1+H8fr6OhwOiUhAMeC2CEfI09OTLHB1dZVUlEI+goWMf9vzoECHVzM9r9PpYGtIL+aOmoxRDLIPdJ5o75vHM2aPMLv1er1Wq0UFib29PXS7j4+PZrOJmYiqIpiGAoEARsxB9Xodr6EOEZfL5XQ6YbTb7dvbWyISlpaWMF1gnsJDa7UaRuoQQe/c3d2FoZAPDN7z2KO9quD7PPbwjNnDM2aPmhU9FuY2mw3jQlb0vOexR3iPVZ+OkUMutKj9/f3Zf+19Pl84HIZRLpfz+fzDwwPRgfLp2MHBQSwWwy6f5LO1teX1eqlPpzs5OXG73YKFjFX3POXW9dueN9s+8p63aHjG7NHm7EZNjcCrYg6gKpQ3P+gIVJJQ7iA/2TXd39+TvviVv+kgWH8hLXrxd2DVJlsP/hxex+zhGbNHOB1TOORSPh3D+P2QS/XpGB6Ex8Hgp2OLRaf7B7JdwRFsP/9mAAAAAElFTkSuQmCC';
      case '777' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADsAAAA7CAIAAABKR2XkAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIPSURBVGhD7Zixq0FRHMcvHtcgDGIykCxKUTIpA4OBWAwGm/InSGTAvyCjyWBSktFgslhkU8qgTCSL7X3dc97rlnvHI1e/z3Cc83m945d3fYZnejwekqEw81fjwD/jy+XSbDaPxyOzoF6v5/P5w+HQarWu1yu3+r7b7cbj8c1m0263uVLQ9G63u9frBQKB2Ww2HA65VfnBYDCfz7mVpEQi0Wg07Hb784CJwel0ymazyk85o9EIfrvdRqNRrhT0/HK5hMfKz39oevwuboDHbVwp/PtOp8OVQq1Ww6cDD4z3VNDE4vlhL7IsFwqFdDrNjiAYDGJ1uVzVahVPD5NAz3u9Xrb2+31mGJoeb4cbsMFtmj4Wi6m93++3WCxsTz0WD/WYevwKTSwe6rF4qMfUYwb1+L0YtsdmsxnNy2Qy7AgcDgdWq9UaDodZUxl6nn0tsKovAZoe3zDcgA1u0/TYqL3H4zGZTGxPPRYP9Zh6/ApNLB7qsXiox9RjBvX4vVCPqcevGLbH9/t9PB7fbjdmQSqVSiaT5/N5Mpmo/w56vlgshkKh/X4/nU65UtD0siyXy2Wfz7der1erFbcqv1gsdrsdt8p/sUqlks1mex7wroB6LBCaWDzUY/F8UY8jkUgul/uQHjudzkqlwh5I3R6jiPAf0mPMhgnhAdVNPF/UYxQR64f0GLNhQranHovHaBNL0i9rKaRIsFqoEgAAAABJRU5ErkJggg==';
      case '333bf' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAIAAAC1w6d9AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAPcSURBVFhH7ZnLK7RRHMfNO3IJ5V4uUS4Tcim3Ihtlh2RloSiysbGTRJRJyT9gK6aGhY2VDaXMyiVGIbmEkEtILiOX99sz35l53rmYmeOoZ/F+Ns739MzM9/mdc37ndw6dzWYL0SR/+Fd7uGK2vr4+ODhob/uivr6+u7ubIjCenp42NzdXV1etVuv5+bm9MzU1taCgoKioqKysLC4uzt7pDpzZWVpaYpdvhoaG+LQ/Xl9fYai9vT0mJoYf9kFLS8va2ho/puJXRvPx8RHvUFNTMzk5iTZ7fTAzM9Pc3LywsPD19cUuBfnOrq+ve3p6xsbG/HpycnJy0tvbu729Ta0g2RlmldFoNJlM1AGzu7s7Nzf38fFBLdcZhsNsNk9MTFAHycrKytXVFYVcZxiU6elpiuC5u7tTTwBpzhCw+fl5i8VCHTz39/cvLy8UEp3he5eXlymEiI2NjYyMpJDobGdnZ3FxkUKI0NBQvV5PIdEZsnzgacIrCQkJCBuFLGfPz8+IGYUo2dnZUVFRFOp98+3tze9Lh4eHR0dHU6hAdm1ra/vhaI6MjCDfUqhjFhYWhnh+j1dbAAv+5uaGQhTs8WwpyBlN2Nra2qIQIicnJzMzk0JBjjN1HhIjNzc3PT2dQkGOM/WuIgacqac/cDlD+sYE/57R0VE+LRuDwYCJTqEgJ2anp6dsCYHqsri4mMKBHGfv7+9sCVFYWJiSkkLhQI6zH5KVleV5GtCEM2RKTGIKB5pwhoC5TX+gCWde0YQzbG7YtSkcaMLZ7e2ts7Bwoglnh4eHCBuFA004Ozo68ixV5DjzVR0FyOXl5cHBAYUDl7Pq6mrlPuE7+vv7+fS/JCUlsSXK/v4+Ww7kxAyHC7ZEwc6Lkp1CQY6ztLQ0tkTBaD48PFAoyHGGYgFFKYUQe3t7FxcXFAouZ6gXsHSRWr4Br+V2l2QnMTHxh2HDInDe+xHObZvNarV6FkludHV14SzOD6jAmm9tbeVDooyPj/PrFOSMJrIGymUKUbAI1HuUHGc6na6yspJCFBxzfuX+DDGrqqqiEOL4+FidOKQ5wwqora2lkIE0Z3q9vqGhISMjgzp4kHrUGVuaM1BSUtLR0UERPDgJ/8r9GcAbd3Z2NjY2UgdJaWmpuuaW6QwkJycbjUaBddrU1FRXV0ehINkZyMvLM5lM+CXqAECZg/dxK1jkOwNYB1NTU2azuby8nF0+iI+PHx4enp2dNRgM7HLgutlDYTkwMIDNxy69UlFR0dfXFxERQe2Pz8/Ps7Mzi8WCenpjY8OZrrD95+fnY9BxOvc8z9n5///N4NGqs5CQv1oWBjjf7yiEAAAAAElFTkSuQmCC';
      case '333oh' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAA5CAIAAAAUWIQbAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAALeSURBVGhD7Zi/jylRFMf9A9vsH7ClbLWFQmJLeVuoFDQiGuIPINlCtdWrFAoKhYJsJVFRyZMIIUQjIrbZQrZYFGyshNC9b9wzjPlhZl7GzsibT+ec6/jMzL1zz2XbmRXLTDsKZt/f34lE4tcp4XB4Npsh2+l0KMQDQaQwAMMoxIFSKLgvrIyC2XK5jEajtlOenp4mkwmy9XqdQjwQRAoDMIxCHCiFgvvCylhmeywzY83MuzYN5JrNBoPBn1OazeZqtULq8/OTQjze39+RwgAMoxBHr9fbbDb7qsoom728vNAE5ji/Amq1GlIXXwFAq9kPrU1gmQm5lBkM4EEhjv/GTNNbA1pfX19Ibbfbt7c3inLo/NYwims20zrP8vk8UmZcm5aZZSbmms1SqRQa5Xg8/psjnU4vFgukJLvtUqmElJ7d9mg0CgaD+H4mk2GveGMhM1yiz+ejm26zPT8/z+dzljIKMuv3+/f39+S1JxKJTKdTljUEMvv4+HC73STFgbs4Ho/ZgAPYqiuVit1up0Gq8fv97IigkuM8Qy9wd3dHZTg8Ho+gHD66XC5Ka+Tx8REPhwopcTTDzahWq2I5QblWq3V7e0s57TidTnZUVuRoBuTk+OUkn7smHh4eGo0Gq3aGEzMAuXK5LJbDxMLjRhZj0AAGAgHxGPWgGjv8nUFoBuTkEEGcyalEvH8cQDVcKo2TQsIMyMnpC+pj8shdqrQZ+DE5uecgawbwBckFoS+oXywWxXLnzMDPyOE19Pr6KpBTMGNIvoT15ebmplAo8OVUmQEs8n/YkTQhkFNrBrrdLvYDKnMZHA4Hzs/s5zSYgfV63W63k8kk9ZBnyWazmAYH8JHFY7GY3NzA9jAcDtlvaTPTC7QFXq+XdHgYbwbQmaI/JSMOU5gBzI1cLsfvXMxiBrAS+X2oicwYaLHQaJnRDODkhmObGc0AzhyhUMiMZgAHbPaXJTCXGR/LTCu73V8wBLc+Fc5oWgAAAABJRU5ErkJggg==';
      case '333ft' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADsAAAA7CAIAAABKR2XkAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAUqSURBVGhD7ZlLKLRtGMedTxkzzsdxTkQapJQkp4XjQikisRBJLKXUpD6ykKzEQlEkS+WwYaGs2CFpGsfk/BlCznz/5r5mmmfGzPsYM/f3vvX+Flz/+/bMe733XPd1mHF8fn52+KNwot9/Dn89tj+c4vj9/X1ra+v29pa0OJydnVNTUyUSCWktnDz+/Pz8RwtpceTm5k5MTISGhpLWwikqHB0dpVIpCdH4+/t7eXmR0MEvjgMDA8kSTUREhKenJwkd/DyOiooiSzRyudzNzY2EDn4e4wLFx8eTEEdsbCxZBvDzGBHp4+NDQgQhISFhYWEkDBB4/Pb2ptFo/hXy+PiILVx25CZa0nF/f88ehEFLOvA6Hx8fbJchk8lwk0iIICYmJiAggIQhyG56Njc3kf9oQ8f4+Di2bm5umpqaaEmHUqlkD8KgJR1FRUUnJydsl3F1dVVbW0vbIiguLj47O6OHDeAXFa6urka1wDK4qaaJAvDz2MPDIzg4mIQI8Md4hIQB/DwG30rJiGOyhHD12NvbmywRmMvfXD0WX0RSUlLMJRZBJ3R3d7exsYE+i7SW6OjoyMjIL5uvoKCgxMREGDs7OxcXF2yR4e7urlAo8JO0FuSi6upqtVpN2jxf9kAMrlOTSqVCgsOhkDZPZWXlyMjIl80T16jw9fX9uiiYgJAw7SgYAo9xBpmZmXgrDZmensYWKl9bWxst6ejr62MPwqAlHWVlZah8bFePi4sLtkhYBPX5y2QMuJ4x8isaSBIWsZAHuXosHgt5kPcZiyx7FvIgV48xO2HYJGEtv2NUWCgfwIV+a0H+q6+vN8rQbBDA2eTk5KCasEVGcnIyM9LS0np7e5nNQPMuMi2Y4uTkhHeDhAm8P3dDHuzp6SFhBvToU1NTCQkJpIX8prnCAoKo2N/f7+7uxrhBWktLS0t5efnT01N/f//6+jqtaiktLW1tbYUxPDw8Pz/PFhloRXCcKHKkteBFzs/PSViLwOPX11eUPaO6X1dXh5+Y8zD2LC0tsUVGdnY2M/CfNNrC1GQ05wG8iFGbZQVco+Ll5cW0dH8X3h4bhZwVcPX4+vraqI22Aq4eHx8fYywgYR4kAI1GQ8IEwc3DgI4siMmCtBbWlCClo7UtLCxkiwyZTKY3jLbkcjkKAQktuHZra2skLIJRyMIF5VdBcGzNzc2zs7OkLTI+Pl5TU0NCCL+oWFlZEekuuLy8JMsETh6fnJygypAQATw2Fxg8PEZcol7ijEmLANXKXLja3WOU5Y6OjtHRUdLiODg4eHh4ICHEjh6jSi8vL2NERSNGS6I5Ojo6OzsjIcQuHiORoTlpaGgoKSkR8+mEKWq1+vDwkIQQ23uMs0EDmJ+fPzMzQ0tWsb29TZYQW3qMLmdwcBDzyMDAAG4brVoLAoN9PWCEbTyGr0NDQ1lZWV1dXWgeaPVn7O7u6r+1MORHHiNeEW2Y8DBLdnZ24lRowxaYu3xWVum3tzc0CWNjYyhjPw8AcywsLBQUFJDQ8b0zhqNovpRKZVJSUl5e3uTkpP3cBXt7e2QZ8GuPkVZPT0/n5uba29vhaEZGBgqYbQPAHIgKBB4JPYgKc6CdbWxs9PPzoz/lDs4I7yF5o8PSGSO57Ozs2OruW0F6evr3vpcODw+vqKggwRGJRIJ/F3FYVVVFSwb8IlcgiFdXVxcXF/XFFhGsUqmYbYhCoWCfv8fHx2MA8ff3j4uLk0qlIj8w1oPJBR67uAiGI0N4f4r1c35UQf4X/npsbxwc/gNmTITS2FS5eAAAAABJRU5ErkJggg==';
      case 'clock' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAA2CAIAAAAZGx0EAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAY1SURBVGhD1ZpbSFRdFMcdGwu16IY3JKOhJKQ0r9k8mIoEERFEEHwTpfhQT9GTvthTCIKpoIL2EMyL+ZAIIjPD9JDNNNR0L1OJFPOC9/ttUvHy/Zm95nbmdvaZUb/v9yB77TPnnP9ZZ+21195H2draWsj/hyDL/fv3r8ViYe2IiIjw8HDWDhaByl1ZWfnx48ebN2+MRuPnz5+XlpbogI3ExMQLFy7k5ORcvnxZoVDI5XI6IAmJcjc2Nj5+/Pj8+fO2tjZ3id5ISEgoKipSqVRoyGQy6uWBWy5+r9Vqnz59Cl9SlxtKpXJ2dvbXr19ku3Hjxo3S0tLU1NTQ0FDqEgluL5LV1VW9Xp+RkUFneufFixcPHz4kwzt37tz5/fs3XV0cYuVOT0/DH4cOHaJbeSc5Ofnnz59qtZpsnyCym5ubMUDpNv4QJbe7u7ugoIDu4A+EJp4NoXL69Gnq8gccgeChm/nEv9yvX79mZWXRhUVQX1+Ps6AYuqlLBPfv38cp7I4+8BPp0PrgwQMkAbL9ERsbm56ejgbCBvmLdYrh2bNnzMdke4NkewIJlcuv4MqVKyMjI+z0jo4OMbHuDFzjOyq8endycrKsrEy8Xxnw6NGjR1n71KlTaWlprC2SxsbGhoYGJHWy3fAsF89RVVXV3t5OtmguXry4b9++iYmJ5eXl48ePp6Sk0AHRVFRU6HQ6MtzwLPfVq1eYscgQzaVLl5DF0MDpf/782b9/PyZedkg8mCOrq6sHBwfJdsWD3NHR0bq6OvFTq51z585FRUWhimD1A3qQVtkDcPHu3Ts4y2NICOVub2+3trYaDAayecCrRwmGofb9+/cvX74g+cfFxZ0/f54O84C5AwOdDCeEchF2Go2GDB7sKQzzamdnZ1dX19TUFG86szM0NITiyd3BQrlms/n169dk8ICXjjprc3Pzw4cPMN+/f9/b24sGagzedMaAXDw5GTZc5CLspLkWsBQGj9orNZPJBPUS0hkDBR17cmdc5GI88iZaO7m5uUhh/f39nz59Yj3QPTc3Fx0djezGenh5+/atYMS7yEV0+yhSfYAUdubMGTQg0X4DRDBCEM8gWS4qu7GxMTKsOOTixfX09JDBCUthEIqcQF0hIePj48gPaEhLZwAPLAhfh1zMQ319fWRwwlIYPAF/UJcVvK5A0hkQeNAhF/XbwMAAGTwIUhjrZASYzgCyOFYxZDjLRZJbX18ng4ekpKQTJ07YU5gz9nSGZRnr4QWStra2yHCWOzMzA2eQwQMC9/Dhw4uLi4JIYLDwPXnyJIYj6+FieHgY4USGs1zJwLWoZlBw4tLU5QRqHYvFgudBBFNXAARB7rFjx/DX28th7gkLCzty5Ah1BUAQ5MJ/KIwUCkV+fj51OZGZmQmhmC+ljWMBDrmophGFZPCAeg+FUUxMzL179wTlAdZOt2/fxkwBx9tnOy4Qac4bbQ65crkcIUgGDyiJWFV069atmpoaFDqsPy8vr7a29uzZs3Dty5cvJRTQAJJcdnrYkg1grNy8eZN6OYFEvV6PBInrQBYKfExpbLMDGePJkyf0O34qKyut6giHXIzfkpIS+hU/GHBYfM/Pz9PlrKBmwuKWfiEJrVZL17LisqWHGr6wsJAMScDNV69eZYUvyh2s3aXFAAOVRlNTE0oOsgFTzfj27RtCjQ78B7h7965g28ElkWHu4d0H2VGUSmVkZCQZVlzk4ti1a9fI2GvgOOQWMmy4yAXZ2dkes/3uU1BQgKRLhg2hXGR7pE8y9g4MIWRVzC9k2xDKlclkGNoSdl+Ci0qlQl1KhjM05FxpaWmRttoOCnAW6hCS4opnuZiKHj16RGfvLnCTRqMhHW54lgtQ+F2/fp2usYuUl5ejxiARbniVCyRsRweI3+1oX3KBwWCQtuaWQHFxMdbSdGMv+JELsDzcBR+L0Qr8ywVYzSK70YV3gMePHwtKOW+IkgvEfwbkYkc+AzJwUZ1OJ+Yjq0gkfGTl/oQN0W1tbSjypW1KMCR/wg7oHwTUanV7e7v/b3c28Or/sYL6fZf+QUAAnA03G41Gk8lkNpvdpUMiqjxUrij04uPj9+bfL7yxtbW1sLDAdrUOHDhw8OBB1h8sgix3ZwkJ+Rfz2MOd9ninPgAAAABJRU5ErkJggg==';
      case 'minx' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA4CAIAAADIJsd3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAe6SURBVGhD1ZlbiE9fFMd/M1OGXHN/csstCjEYI9c0SaEYlyJ5QC5FXigPeHMtKQ9IoSnSUKQQD4YGE8K45X7LfdzvlBkfv7Vmz5nz23ufM+PXv/98Hpi9zz57f/daa6+9zkzGz58/E/WETP2/PpB+rWVlZXPmzCkuLq6srNSuNJFOrYTT7t27x44dW1hYWFBQsGbNmq9fv+qzdJC2eH316tXKlSt37dql7STjxo1bvXp13759tf1vpEErvj537tySJUuuXr2qXQFatmy5du3a6dOnZ2dna1dd+dcY+P79++bNmydMmGAVCu/evZs3b96yZcvKy8u1q678k10fPny4fPnyQ4cOadtLTk7Oxo0bc3NzMzIytKuW1NGuFRUVR48exZwxhcLFixcnTZq0bdu2OlunjnYtKipavHgx/tV2bSBm5s6dm5WVpe3Y1Nqu3759w6ikJNJT9+7dtTceHTp04C2yL0I/fvxY6wSMXWPy6dOn7du3c66XLl364sULeu7fvz9t2jSdKIoxY8acP3/ezNO+fftVq1bhmeTcsYir9fPnz2RKXTaRyMvLO3v27I8fP1gYn7IBfWCjadOmHME3b94wz5MnT2bPnq0PEokpU6Y8ffpUlogkllb8zr8bNmzQFZKgD5VoRTG6Ua8PakKcHDx4kNTGsGPHjvXp00cfJOG0vX79Wp7KWh4itCJl586dOAu5JSUlOE4XqQIjYSpGEhXEhvZWQYQQJzzF10yCgfVBFfgKlSdPnpw/f36kgX1aWWbmzJnMOHr06MePHz979iw/P1/WCIKpWIwlMc/evXvlwBmrMw/XBJetDA6CdHlRoosETMXjMbBdK6viOHPMmRT3mUlTYcCmTZtEGTskOuUYUbtw8Dn+Oq4m7Jz9B03APOvWrfvw4UNSRRiLVg4Bi4X8ZZwV6g8yY8YMiQeBqMCz+syGa86JEyfevXtXZwkQ1oo9SC76UoBUG6SC36mz8IlMdePGDetUAvo8vjInUqYSqrXirx07driyD1NjAE7YihUrtKsm5IHS0lLmIRJOnDghCdhjWv8ZAFYMJWDVyhn0+wvEZRgjNQzM7WDSp0nALhOwZ3buDyoIxsNfrVhi4cKF+tANr718+fLRo0cjRozQrqSzOPuSIEPpM5gKQqFlAmD9+vXa5Wb8+PGsq1ph69at+sQNyZUUizEoRqUH9bdu3eJ1V/oEk2KDR1YCgFuAu0CGeWA5uYxU6+XLl3v27KkP3XB1MfjIkSMsaZKLK30asP3hw4exokmFEgB8TaReLqkcOHAgqbFKK4aZNWuWPnQjVyKfVtevX5e19+zZ40qfQdibOSjE9J07d/hhy5Yt+tjNkCFDasSrEOdNZEmSB+ul6sfEDFATRp5mWLRokUQ8VGulbu/atasOsWFcyWBOmN/vLpiEsy8rEjyeBCyQsGUwVNfanTp1Gjx4sDZSQNn+/fvJheZrqW7f/nhDf0okevToUVhY6HEOWWXAgAHaANWcxBoGoVBbsGABB5Fylm8YHVEbyHf4hJzA65KACXpT8YTgCFnuAiH1YDJFavVJgmPwvn37ZEytQCL7lHiLrMVkIUMNraGEZ1IjuYkMZdKnbPfatWuhwjkOkoCCDnTVuGyGLf2VVUUNrSDFf3DHnFzOr7wvIBGhbIDPUe2Kx6BBg27fvo2mUH40p9YkYDqp2uSzxxDWShiMGjXKRFKwig0ixzP026tIJAFZ753gqZAaH9snFVUT1spc79+/5wdrFWvAotg15m1nIMSZ2bNDQpbADcoIEtYqRGY+lzc9yCuRkYMbpRhSKQEsWu/duzd8+HB91U2kkUJIAMQ5kTizqKhIxASx/N6lUaNGDRs21Iab06dP8z65OmY2YP/Z2dlnzpzBadrloF27dp07d9ZGAIvWVq1aRV59cOHCBS6hjh07Dhs2TLvcEAD9+vXjquPUapcbNm+th+y/e6OwwFkVFRXadtCrV6/WrVs/f/6csNEuB02aNBHzY9QvX75Ip5XMzEzu3jZt2mg7QNp+B/8f4NR6/PjxyMBq3Ljx1KlTmzVrRhqmztfeFDgAMoxLCydorwOCtaCggFe0HQStVij+dYQXuTP9n0ByJ5OwiFrtciOfHlacv38lFoPfgC5OnTr169cviknPpYBEPHDlyhXqdO1yQOXEh4A2UnBqbdu2raecNZAN+MgkG7hsRgmSm5vLfshW2uWGFT31vlNrVlbWyJEjteGG+oGwxmwurSxPFc9+2JV2uRk6dGiLFi20kYJTK3Tr1s3jEYOEAcazmoQZuIfYD7vSLgcEQF5enuevND6tvDxw4EBtuJEwsH4CmQBgP9rlhgRsva4MPq0NGjSIc7wwGJ/FGC/1ApMAePv2bVlZmXa5wahcmdqw4dMK7DVOGBQXF//+/RtloWwgAXDz5s1IuzIMu/j/TBehlczcv39/bbjhY6O8vDyUDSQA2AM70S43BFuXLl204SBCK5VRnPqQkH3w4AHZAD9qV9KnLM8e2Il2ucnJybHWAEEitAL1UeR9w6dpSUkJP/D9YwajFfXsIU62Ij9G/iUxunbBiaWlpVw5/KBdNnr37p2fn19ZWUlde+nSpebNm0+ePJlvTLIVpYUOcsC7aLXXAAHqU50VHQP/H+qP1kTiD6FWRn1nMhhcAAAAAElFTkSuQmCC';
      case 'pyram' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADcAAAAyCAIAAAB3dNSiAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAU6SURBVGhD7ZhLKH17FMePV2cg6khehZSBEaZMlJmSAeEODA6SMjIz80wGMqXIK+Jcj4GBUCKTqzDwmMgjeb8KeZM/92uvdX93n73Pb599ztl1/+p+Jn5r/R57ne/vt9b+bUFvb2+2355g/msRvxTYsA4ro/z6+vpTAQ12WYSVO354eOh0OtEYGBhITk4mpyVYpuXHx0dvb+9fCmjA5A4rsCzKjY2N0dFRaqMBk9qWYE2UT09P0O/o6IhMNDo7O+/v78kMHGuiXFhYGBsbY0NhampqaWmJjYCxIMrLy0sI+fDwwLYCTDjRxXZgBBolis74+PjMzAzbKuBElyVVKdAod3d3BwcH2dCBLgxgIwACihK1Ftu6ubnJtg50YUDgJTmgKFdWVlwuFxsSMADD2PAX/6NEocE75uLigm0JGIBhAVYl/9+QeLsgkT8/P9mWExwcHBERERoayrbv/Iybm/9R3t3doZKvrq6enZ2xS0dYWFhGRkZ8fHxpaanD4WCv7/gT5fn5ud1ux1P7+vpqamrYKwdvy4qKisfHRzwrOjqavb7gc/a8vLy0traOjIygXVBQkJ+fT34ZGIBhOL49PT3t7e1+bh2m+cT09DRSIS0tbW1tDebExARMXksHujAAwzAYU2BiurKMb/im5fX1dXd3N1J7e3t7eHgY83Nzc0tKSrhbB7owAMMwGFMwEYfk9vaWu82jxGqK19dXnDCeZrPFxcXNzc3Bj2tvUlISe1XAiS4MIPnZa7P19/djKWVJs/igJW6NkIQNpVxDVwiDLEZysFcFnOjCAOinvjHhgIqbqFk4Wm/gnltXV8dzVJAwOzs72dnZ7FKACadGfkFLS8vz8zMvbQKzWqo/GNSQMNjcsrIydinAhFMjvwCz1tfX2TADR2sICnhVVRVP0EHC4AAUFRWRBw2YkL+xsZE8erAgluUHeMNUlMblRmQJkgkp5TWrCJ+qkvcdR/XBpUZ9/DVgW3E6Ue2zsrL+UEADJpwGWYIFu7q6sDjbxnC0EmTHX4Oo3sgYgIax/AIsbqYqeXmPHx8f19fXX11dsS0nNTW1oaEhKioK7Zubm6ampr29PeoyICYmprm5OTExkW0JP+Pm5vNt479B2XcpBwcHOTk5PNSQ4uJipALNQkNTPmXk5eUhw2iWAVItl5eX9/f3ExISysvL2SUH1ae6ujoyMhLFH6DhdDrh5G4JSK/KysrY2Fg8aHFxkb0e4WjdOTk5wb0Qr0RUZnW5llFbW4vvLyQNngrQgAknd0uA3lCd3r3GonqIEqWho6MDq6Am4yfCMz8/byBMeno69MMwqj6AqtLW1ha6eJAO8S4Qi+OhsqrkIUr16vRzjYWh1aEE9CAPCSN+rUdoo9QnWPxaPdooNQEJYTDfozDILWSYPiB96GqwFLTAspriTydHCcQNbZT6zcUBxTH1KIzBb5DFQdArR19A8GgEoATihluUsgoiE8b4PJAw+jUNfjag+xQH9A9uUeJWwWPd8SiM/vhrEMKoL0dCfoPcQhgYoObfKI0LOAmjvmiaqVMkNtUa8tC1UiY/Qfd8DkuBo5TpLxDC0DerWEgmv4CEwWBM8Sq/QPPJwVEa6C8gYTC5ra2NPnfMvD9FEUDG0LNlp1+N+N4nvqNU74gxJAw+C7FleB6eyh2GUPJho3EDxPShoSF91utRf3J839xOT08nJyff39+5X47D4cBVPDw8HG38ttnZWehEXTJCQkIyMzOx3Xa7HSZmuVwuM/84CAoKKiwsTElJ+W4jSvL+zvyM++X/UVqFzfY3A7kdYUPLJqwAAAAASUVORK5CYII=';
      case 'skewb' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAA3CAIAAADSR86hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHzSURBVGhD7doxjsIwEIVhdiXoKKHgGNTchJIb0FOl5wochYaaI1AhkLgAApp94nmXCIhjz4wTLO1fhOC4+BSRFNhfl8ulk0/f7jOTHnd3u90uFguey5pMJvP5vNfrnU6n4XB4vV6Xy+Vms3GXRRVFMR6P3RcELluv125I1Gw2Ox6P5/N5tVoNBgMccY4RjLsZoqByvns23LK13+9jBEeK9/v9dDrlNEH2XGhgKluZidiYW2VlerEl129lSrEZN8TKNGIbbriVicUG3Fgrk4m1XJmVCcQqrsbKYsVyrt7KosRCrpWVhYslXFsrCxRHc1NYWYg4jpvOymrFEdzUVuYXh3KbsTKPOIjbpJVVieu5zVvZW3ENty0rexX7uO1a2ZO4krvb7Vq3srIYKue79+CiT7CyP7GT/fbgfo6VvRVn9i9Otj+GzB61zF5kuIDZ7YqfrBip4aK2xK9WVM9FzYvfWlEQFzUprrKiUC5qRuyxogguSi32W1EcF6UT11pRNBelEIdYkYSLbMWBViTkIitxuBXJuUgvjrIiFRdpxLFWpOUimVhgRQZcFCuWWZENF4WLxVZkxkUhYo0VWXKRX6y0ImMuel0QZnorsucizxK2ctE9CReVxek2CNhvv+h2u4fDYTQa3W438+0X/3txUpYVt9P5AbrO1WmVrWABAAAAAElFTkSuQmCC';
      case 'sq1' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADYAAAA1CAIAAACFs48kAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAXtSURBVGhD7Zk7TFVLFIbhSgxvhADRAhBEIy8RJRAaCCSaYGGhoSKURiOJJQkJhAoarAg1gVCT2EBDQWIwRMMbDchLeSogbxQ0In6ete/cYR/OuefMJjcU9y907bVnZv9n5l9rzQyB379/Dzjb+Mv6/yyDWQRjY2M3btywXD6gsbFROk5NTRUUFFheNzx58mR7e5tma2trZWVlltcHPHr0aGtrSz5hOIvDw8O7u7sY0dHRKSkp4nTHlStXgoODMebm5oaGhsTpLwwpMuufPn3CiIiIuH79ujjdkZOTI8bbt2+np6fF9heGFEdHRycnJ8W+ffu2GDYggKSkJIwfP34MDg6K0wDm4fL69evDw0OMy5cv37p1S5w60tLSYmNjMdbX10dGRsRpAHOKyHFzcxMjPj4eNuLUgTM0NBQDSbx//16cBjCnyFrPz89jhIeHX716VZw6lBAHBgY+f/4stgHMKfJVvo0RGBiYl5cnTgUlxP39fSerDMwpAiKGUMBISEiwpdXMzMy4uDgMMiLhLE4zOKLI9BAKGJcuXcrKyhKn4Nq1ayEhIRjk9r6+PnGawRFFUsmHDx8wbHIkWebm5ootYnACRxQpMP39/Rg2OZKDkpOTMWgwMTEhTmM4oghUJdTlyCpfuHABg3RDHRKnMZxSHB8fX11dxdDlmJ2dLUIknshN4jSGU4rI8ePHjxhKjghRppPaQwX608gZLIqUgdTUVEaXR7/w5s2bo6MjJUeEmJiYiLGzs2O2yjExMRcvXjx37pz1LHsyAVu03t7euro691TsBQ8ePGCt6S6bzmfPnqFOHokkfrbVyAcUFxc3NTUxyNevX110LByjqIPi0dnZWVlZifatMTyALI3g6PLly5fy8vLW1lYZAcNq4RkMXl1d3dPTs7GxIb3c4ZGiAhUMtbW3t/N5lsAa+zg6OjpoeXBwUF9fT6LGZiKZTuv1cSCDiooKulDi6eL6iDf8czAoKiqqqqpi5paXlz31ZAloyXLcvXtXFy4dv337RgN0ubS0hLG4uFhSUmK9dsXQ/fv3m5ubiXHbOirg5y1tHj58+PTpUzlRgJPPLsw/S+ydri7c0tJShGG9cIG5RPLI6/nz50S9qNMdQqulpQVa+hLpZ5eTKeqALqekFy9eeKGLkmxzs7Kyor5hg9Bqa2vzohz/KOrwZXZPhKKFCiUleYc5RR3QFe3alliBOGOb4zstHadwSPULv3792tvbsx4MIEz/m4V2DwtP0GcxyPJ5BrTu3Llz7949ziKMTqGzXvwNqh9JmxIaFhZmuVx7HA750dHR8hgUFMQ5ARAiP3/+JDGRDfipkrSljUcIU4OkQ9Hr7u5GjjRWNVDh5cuX5MLCwsKGhgYS0OkkHV9SN18iyZHqSHjWYC7U1NRIl1evXlGKMPiXAa3XWuomgAgj12B26MmINGen6AW+F0BAAWTtMLwXwMePH3tPtDo8UvR9G4FCWAS6yDaCqZIRfNlG3Lx5k20EulRz5o5jFGlnsBmDFuToLoJWMpIaaDX6N6AE6r63zdjMzAyS13cGvkPdNXZ1dfHIIR/B8UjY8lVp4xeQU21trYowK3WzT5mensYrj35BLkZIPWxzMDjYs83BIOOwjn9a+AnSEDKTOy3gtLqoixHqB5OHwe+Ukys7+/z8/D+NnMEpRXUxop9HyR3kAQxCzd/S7w6nFNV5dGFhQZ1HWeu1tTUM94sUAziiSMCqK1r9YkTJkfgzk6MORxTT09MTEhIw0J9+MaLkCDIyMsQwhiOKCDEqKgqDAj0+Pi5OgZIj538vf/XwBY4ocqo/f/48BhXSduEORRI4BsHELxGnGcwpcoxX33a/oVP3egQTISVOM5hTJJvIdt8mRAHOd+/eiU1I+V4J3WFOkViJjIzE2NzcnJ2dFaeOkZERkSO/xEl2NKdI3ZMduKerYiVH40ooMKTIrKhNmlpQG5QcqYRMuTgNYEiRmkHlwGD/YUs3CrocCSy/bsl0GFJk4WTnxk7RE0VwKnL8/6/6p4EzTzEg4DckPbPZ1pBcUgAAAABJRU5ErkJggg==';
      case '444bf' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAzCAIAAABaAcxDAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAQiSURBVFhHzZlLKHxtHMddh0Qur1zeRKJxmxQLNpYvWVhNcgllYydsFGNhJxuK7VhYkCJhIfYTKbcGRW4JuRuXyJ3/9z3ny3v+ZvxnPPN4m89C5/s45/ie8/s9v+f3HN4PDw9engdtvb29XV9fPz8/q6NafHx8QkJC/Pz8qP8XaOvu7q6xsdFsNqujWjIzM/v7+/V6PfV3eH193d/fn56eXl1dtVqtT09P6nhycnJaWlpOTo7BYNDpdOrgb8AWuLy8rKmp4dDvwNby8rJ6muvYbLbu7m78Vd7lC/C0XV1dOJmXvePD38sD+TA/P19UVFRXV7eyssLRL1hfX6+vr8cbOTk54ZCCZFvwNDY2VlZWhsBxyAWGh4c7Ojrwkqil27JYLMjR3d1dapeZnJzc2tqikGvr+Pi4s7NTwBNYW1ubmpqikGgL4RsaGpqYmKD+PqenpzySaAsvCSlC4TasW4+PjyMjI3t7e+qoloCAgJKSkujoaOovGB0dLS0tpRCitbXVZDJRKGXCXf5Q9lwHtng7WXULaeG0RDklPj6eR7Jy6/Dw0H1bCQkJPPrIrfv7+/b29tnZWXVUCx6ira0tPDyc2hEDAwPV1dUUQmRnZ/f19SUlJVGrsfxDcuTn5x8cHKinfQXSgmeLYjQasf7wdlJyC28ahZRCFPQUwcHBFFJyC90L6guFKOnp6b6+vhRSbKFXc1jwXCcmJiYlJYVCQc5MdBN4io2NpVCQYOv29vbm5oZCCHSqn2a6c1tI5/PzcwpHIOXhjEII1IXAwEAKBY8IYkZGBo/ekbDzQeNbUVGxtLRE/U1w8/Hx8dzcXGoFvi1vb+/Q0NC/HIGo/+huLDEx0X4J8Ygg2kNbCOLV1RVS256LiwuHwZUF1hz7iUxbmE0tLS1/O6KgoGB7e1s97Sc4Ojqyn8geEUTsL3j0jgRbWMvcnBPYB7y8vFAoSLAVFhaGCUshxObm5qf08ogg7uzsnJ2dUShIsIUIoiRSCLGwsIBOk0JBgi2dTudmEMGnrJdgC6us012kU7CCaXtJ2sLiExkZ+Y8j9Hq9v7+/eppDcC36OApRNjY2tNWLS7WbWCwWPACFEJ++OcqZiVgMsKOiEAINiHYyyrEVFRWFDpNCFJvNxqOPILr/acRsNtfW1lII0dvbW15eTvHvZlHGJ93FxcXU1FReIwRs8V4SP+miHy8sLKQQQruwSrOFWFdWVgq/MJSY/z5ASLQFDAZDc3Oz2EKEXh7dM4VcW6irxcXFTU1N1C6DJ8GF2o5epi2A/GhoaOjp6YmIiOCQM+DJZDIZjUZqBcm2AJxVVVXNzMygXjg1l5eXNzg4iCf51Eiybv3Qv6KwzFmt1rm5OWxVPv4VFRQUlJWVhS0rfsbFxWEfqp6sRcL29SeQs1RLR35uScDL6xfpNcUFY5Q7CAAAAABJRU5ErkJggg==';
      case '555bf' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADEAAAA0CAIAAACsM0f4AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAQNSURBVFhHzZlLKOxRHMfdIddzwfV+RSHJY0EKU1JXNiN2kgXZ2FizsECh7C1sZKTxzG6KslB3MYhkWIg8St555BWScb/////3n+bO34yZc86Y+1lM/++ZM2e+c56/35kfr6+vAf8ZkiebzXZ3d4dXKlOJjIwMDg4m8Y1Inq6vr5uamhYWFqhMZXFxsaysjMQ34kNPt7e3W1tbGxsb+/v7e3t7SmFSUlJubm5+fn5RUVFUVJRS6Aw8nZ6eVlVVkXYAnvCut7y8vFitVvxIDD015IL6+vrV1VXUp0+q6Oh9QTw8PHR1den1+tHRUTxTqQumpqaqq6tnZmY+Pj6oSEakp8vLy9bW1oGBgS/d2Lm5uens7FxfXyctI8zT09NTX1/f7OwsaY85Ojoym83v7++kRXlC54+MjAwNDZH2kuXlZXQYCVH70+7ubmNj4+bmJmkvKSgoMJlM2dnZipT6SafTYVn+0uChIXTS3NwcsyEtAsbu4uJifn6ehAgkT9gzDQbDTw0Wi0Wp5J6DgwNsMyREIKCf1tbWPF/8nxIfH4+pQoLfE3ZhHB0kWElPTw8LCyPB7wnbEr+ntLS00NBQEvyeMBcxx0mwgvOYnmR4PeHwPzw8JMFEXl5eSkoKCRleT4+Pj5wTPDU1NS4ujoSMtI8DRDl4pTIVBDoxMTEkXDAxMdHc3EyCifb29u7u7sDAQNJA8cSM0WikhlgZHh6mtlR4x87xPGcgISEBo0FCRRo7zInx8fH7+3sqU6mrq8vMzCThgv7+/p6eHhLeU1FRgegvMTGRtAI88cS+iCqpNhOIJq6urqgtFd6x4yQ5OdlxB1fwsyds3/+sOBk/e/oUP3t6fn7Wrlw/e1ImOAkVyRNiX2zwvzWEhIQolXwHYgqkAiTsKMuPmcHBQWqICeyZS0tL1JYK79hFRETQExPn5+fa8EvyBGsrKyt/NGCwlUo+5ZNQB4Z49nGGxNeJlpYWBGHUnAzv2EVHR9MTK9ppzusJARayWBJM7OzsnJ2dkZDh9YQE+su4zz3aac7rKTw8HJkQCVacpjmvJ5zqGRkZJFg5OTlBnkiC3xNwyoQYwJHneFUneUJebDabaSE64OEFa1ZWVmlpKQkRCOgnxGWVlZUkRCDAE4Iyg8GA/Jo0N5InV3c9yN2USl9SWFjY0NBAwnucok0B/QSCgoLa2tpqampIe0l5ebnjnaAYTwD5dW9vb0lJCWmPqa2thScSMsI8gZycHJPJhO8g7QFY2vglsbGxpGVEegKY6WNjY5OTk3q9nopcgMO7o6Njenraft1rx91/QEajkXnm2my24+Nji8Wyvb1ttVrf3t6UchzYyHqLi4uxLHAuKYVO+MoTD+7u7HGWOV7pfRuSJ3r8TwgI+As6TRu9qc6MAgAAAABJRU5ErkJggg==';
      case '333mbf' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAAA5CAIAAADoTa/RAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAdwSURBVGhD1ZpbiE1fHMfPYNylhCQhoZRmRE2NJlOaPCiUexkvJjHlrsgt08jDGPKiaeYJuZMSZYgIGSW5DJOiaNzvgxm3ieFj/35n/dfss88+++yjc/p/HmbW2muvtb577e9vXfZM1o8fPyL/Hzro7wDcv3//7du3mskQQeVeuXJl9uzZpaWlb9680UuZIJAZLl++XFJS8uTJE9JTpkypqqrq37+/FKWZxKNbV1dntMKpU6eWLl36/v17yaaZxHJzc3MnT56smUhk8ODBCxYs6NOnj+bTi58Zbty40dLSUlhY+PXr1/Xr11dXV6N1165dkyZN4kpNTU1xcXE4V7S1tT179oz31tjYeO/evQ8fPsj1gQMHjhs3Li8vb/To0Z07d5aL7UCuJ+fOnUMcnDx58vv377S4bNkyk168eDF18fHTp0+1QjA+f/58+PDhgoIC6T0e9FtRUUFYa7Uo3nJFq6kpKqXIaBWSUlxfX2/7KiFFRUUNDQ1a2cFDLnfk5+drDYecnJy7d+9ShAfKysr0ahSucF3q+nD+/PmRI0dqncDgNyZ7bSLe6NpN/5PRvXPnDo7UOsnQq1evM2fOaCsuuXiAqCcISIti27uo3L1797dv31zepfTs2bPz5s2Lp5sGp02bJt2HYMuWLdqQLdf4lY5F8cWLF2tra+3Y4lmNYmYGbhOtUtFzpLmBZeVvt2FZuHDhx48fpTWVa8cWGMXgevtGMUW2ViFWMVPVxIkTtTgUtty/ywR988bNugXsEJgOJY3tLly4IGlobm4+ceKErGqtra3MnXbFq1evUlczDkzedvVUEdUM4ZIlS+SK8StzZFNTE6V25Bm/vnr1ip8896ZNm6SIpW7fvn1clDaBGWPNmjVSGhrme8ZIGvzPu6LYaJUs4h4/fkypKLZja/jw4Xv37jWKY7XC8+fPWQK127B4hxog8datW6LV+NUovn37tiu28LFRzEt3aQUu8lTSTmiOHz+uzbnkCrZWwQ4gV1AaxVLq4vTp03pfWHhanlmbk1CLpVOnTpqKISsrq2vXrpqJRLKzszt0iLute/TokabCwtAMGDBAM6Cy2yPGlRvM0GIGJgESZoA9/WqzefNmaSQ0vOdPnz5pc55mEEyomdhCovExkccez18r3bhMFYLKykptziGuXJCJzGiV+kYxany0AvHHDC+1QsO4aHMOfqeJLl26dO/e/fr16/RqH35WrFjBLgkH42O56Mnv379//fqlmVCMHTuWDbtmHBIffnjpU6dO1YwzFUyfPr1v376ajw+LJUbSTCiGDh3q6iix3B49epSXl0vkoZXDz5w5c/zH9V/BLNazZ0/NOCSWC6KYA3A6tQIB07FjR804BJILKN6+ffvcuXPTphWGDRumqShB5WaEbt26aSpKEnJfv37N5KWZDBFU7s2bN2fOnLly5cp0ftVjbtFUlEBy0bp8+XIm4AMHDqxduzZtil++fKmpKInlcpoQrZJF8bp169LzjYzlk7VGMw6J5bKujBgxQjPO1FtUVJSeb2TIbWlp0YyDn1yOawxtv379KioqOGxyxSwTnGr27Nnj7wo2lj4b0SBwGnDJjbvFuXbtWl5eHgce2WRQs7i4WHbibNZwMHXtA3MsqW9x2OkiQ5tz8JYrWqUOSwsbXC4Sp7ZWwUfxP9mR7d+/X5tz8JDLEaCwsFBvdzAnEDywY8cOvRpl9erVbDWlrovUt+cbN260t6ke3iW2UGA2uPiVgy77MtKs4BhXfCzMmDGD/SRbTc23B99rKizuaFPZDniAF83r5oE4vqMYrcavPOiRI0dI8/ZFMVrlXHTp0iUmO6ZJacfAIVZ6CU1+fv7Dhw+1OdsMxq+cWEQxO/GDBw+KVvErD2AUl5WVGa05OTmUxvo49YO7K9pUrh1bIIqlyGgVjGIpNVoFl2LSKX4gA07/2px4l75Zq8y6BUePHmX+kjSz76FDhyQNnIJ4xTwDaSoeO3asvr5eigAL2d/IevfuLaZPhXZ/yRPV7969W7RokVwxx3HmASAhPpZS41daoQi/lpSUSBFGNx8nDanbl/VI27K9Kx0breIBzjwkjGI7tggCcYVU9NQKBIrrTwfJ4i0X6JhXabTK3Sby6urqxJfGr3bksZTEagVKt23bJk2FI65cwdYq2JHnii0UyxdLKfXkwYMH48eP1wrJ4w41F21tbayfmnFgK/PlyxcSbOc4UNilTQ6aicOQIUNWrVqFWzSfDBMmTDCflv+isttjR57xa0NDA25hIE3koaC6uponkVo+cA93hlBcVVVlvzpvuSCK7djCA5IVxcz/AbUKOJsJsd1QJQJPGhMKceUCL13utv1qFL948cIztvwhKMvLy820GI+CgoLa2trY9hP/PwMLaWlpqb0WzJo1a+fOnalsX1pbW1l9WJgaGxtNy9nZ2bm5uaNGjSIuBw0a5PnZOLHc5ubmDRs21NTUSBb/VVZWzp8/P8WTQjj8Dj8C+rZu3SqRl1mtEOifW4AxZgM5ZsyYDGqFoHLh58+f+MnTUmkjib4Z1MxqjUQifwCjdIte85FB2gAAAABJRU5ErkJggg==';
      case '333fm' :
        return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAIAAAAn5KxJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAViSURBVGhD1ZltSFNtGMfVQAt15nAoakIgpZIlYr5N0ezFNgQLQnMoI1HBL1FfFPxggiDqHr9YhNCHSKTsQ2HvQUNtGZb6wU2kF3JYOl8QfM2yQe35s12T49nO2RmdM5/n92Huf59z5L/rvu/ruu7N/9evX37/BwLo73+e3TG6tLTU29tbUVGRnJwcZAdvdDodxukOF3Zh6l+/fn3x4sXl5WXSDI4ePXr9+vXMzEzSDHwdUcTl0aNHbl0Ck8mEMBsMBtIM2BGFHB8f5w8zZiolJQWvpL1henoaVkZGRki7Iz09/fbt2/Hx8aQdwBOTubm506dP0zUOcANuowe8pKuri/4LL7W1taurq/SMHZ9OvdVqtdls+JxyuZyGOOjp6Xn37h0JOz41GhgYWFlZ+fTpU4vFMjs729fXV11dzWWatbR2Jz0FBAQoFAqVSnXjxg2z2fz48WO1Wk3X7BQUFCQmJpKwsztGmezbt6+wsPDhw4dGo7G8vNwxqFQq9+/f73jvwHdGP3369I8d7Gh4+vnzJ12w4+/vn5CQcOvWLb1ef/bs2ezsbIzQNQe0qZxItOu3trba29vpeScnTpy4c+cOqhHd5ASfAfeTcOKjiC4uLr58+ZKEk4GBAa1We/jw4cbGRmbxxApmh9NnU//hw4fR0VESO0GVamtrw+5B9UfkaNQFXxj9/ft3f3//xsYGaXd8/vwZ0UXR+vbtGw3txBdGZ2ZmBgcHSfCCzzM1NUViJ76o9UjspaWlJHg5c+YMckJERARpBpK3eZubm1euXOnu7ibNCzLD5cuXXXcSkHzqv379yt8rbRMVFeUmfTqR3Ojbt28/fvxIgpeTJ08i55NwQVqjKysrr169IuGJ3Nzc0NBQEi6w1+j379/v3r27vr5O2h0ymUyj0YSEhJDmBrnzwoULCwsLpLlBLO/du5eUlETaFRhlImIJ/fHjR0NDAz3jCfR7rE6ZhYRTj6rIan55OHXqFNooEu6Q0Ojk5CQSOAlesrKyUlNTSXAglVFM1rNnz0h4AtsoJiaGBAdSGZ2fn+fqQlhgp6Mj2bNnD2kOpDI6PDwsMM8fP36cdepwiyRGUTYFrk6Afj4yMpIEN5IYFatsMpHEqPCyCZeHDh0iwYv4Rr0qm+jrwsLCSPAivtEvX768f/+eBC8omxkZGSQ8wa71f/78WVtbwytpd+DwhTDglTQDm83W2tra1NREmheUTZ1Ox1+QthG5cUb/cenSJYFb/v79++fOnSPhCZGnnue0ySI9PR3nGRICENOokNPmNvn5+QcOHCAhADGNWiyWN2/ekOBFYNlkwl6jSC5oIrkO1w7i4uJaWlrCw8NJO3nx4oXANQeXOG0i25MWAowy+cvGGfNuNpufPHlSV1fHk8lx2nT9dokfkTdTYGAgGjak8ebmZqPRiPp07do1zABdtiO8bDIR2SgTJNqDBw9iIZlMpr6+vpycHMc4/2mTC3GMYsZR38fGxnD8sFqtNOoEKV2lUj1//ry3tzctLY3/tMmFOEYnJiaKi4uVSmVsbCxMYBF3dHRg3pkVLigo6Pz583q9vqSkhIa8QRyje/fuDQ4OJuHnZzAYMOPHjh2D4wcPHjC/XEZ0mXcKRxyjWIsIJwkGQ0NDGo0GJ0wUAv7+wSPiGEVO5ZlQrF2s0atXr3L9sigEcYwCRLSoqIiEO7rskPAe0YwqFAp+o8imqO8kvEc0o6CwsDAvL48EA7lcXl9fjzYAeZ6GvEfMfhRdc2dnJ4onaXsUq6qqtFqtd2XdHSI3ztu/ch85cqSmpqasrEwmk9G1v0Nko2hJb968GR0drVarBZ4xBCKyUekQczNJiJ/fv0VAgn/m5IX9AAAAAElFTkSuQmCC';
      default:
        console.warn('This event doesn\'t exist? ' + eventId);
        return '';
    }
  }

  csvForCubeComps(wcif: Wcif) { // Not used anymore
    let csv: string = 'Status,Name,Country,WCA ID,Birth Date,Gender,' + wcif.events.map(event => event.id).join(',') + ',Email,Guests,IP' + '\r\n';
    wcif.persons.forEach(p => {
      csv += ('a,');
      csv += (p.fullName + ',');
      csv += (this.getCountryName(p.countryIso2) + ',');
      csv += ((p.wcaId === null ? '' : p.wcaId) + ',');
      csv += (p.birthdate + ',');
      csv += (p.gender + ',');
      csv += (wcif.events.map(event => (p[event.id].competing ? '1' : '0')).join(',') + ',');
      csv += (p.email + ',');
      csv += (p.guests + ',');
      csv += ('"",');
      csv += '\r\n';
    });

    const filename = 'cubeComps-' + wcif.id + '.csv';
    this.downloadFile(csv, filename);
  }

  staffExample(wcif: Wcif) {
    const content = this.getContentForStaffExample(wcif);
    const filename = 'staffExample.csv';
    this.downloadFile(content, filename);
  }

  getContentForStaffExample(wcif: Wcif) {
    let content = 'name,wcaId,run,222,333,444,555,666,777,333bf,333oh,clock,minx,pyram,skewb,sq1,444bf,555bf,333mbf\r\n';
    const staff = Helpers.generateStaffBasedOnPersonalBests(wcif);
    staff.forEach(s => {
      content += s.name + ',';
      content += s.wcaId + ',';
      content += s.isAllowedTo.includes('run') ? 'x,' : ',';
      ['222', '333', '444', '555', '666', '777', '333bf', '333oh', 'clock', 'minx', 'pyram', 'skewb', 'sq1', '444bf', '555bf', '333mbf'].forEach(eventId => {
        content += s.isAllowedTo.includes(eventId) ? 'x,' : ',';
      });
      content = content.substring(0, content.length - 1);
      content += '\r\n';
    });
    return content;
  }

  csvGroupAndTaskAssignmentsExampleImport(wcif: Wcif) {
    let csv: string = 'Name,' + wcif.events.map(event => event.id).join(',') + '\r\n';
    Helpers.sortCompetitorsBySpeedInEvent(wcif, '333', false);
    csv = this.addRandomGroupsForPerson(wcif.persons[0], csv, wcif);
    csv = this.addRandomGroupsForPerson(wcif.persons[1], csv, wcif);
    csv = this.addRandomGroupsForPerson(wcif.persons[2], csv, wcif);

    const filename = 'exampleImport-' + wcif.id + '.csv';
    this.downloadFile(csv, filename);
  }

  private addRandomGroupsForPerson(p: Person, csv: string, wcif: Wcif) {
    csv += (p.name + ',');
    csv += wcif.events.map(event => this.randomGroup()).join(',');
    csv += '\r\n';
    return csv;
  }

  private randomGroup(): string {
    if (Math.random() < 0.5) {
      return (Math.round(Math.random()) + 1) + '';
    } else {
      return Math.random() < 0.5 ? '1;J2' : '';
    }
  }

  private downloadFile(data: string, filename: string) {
    const blob = new Blob([data]);
    saveAs(blob, filename);
  }

  // TODO Alternative?
  private isoCountries = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua and Barbuda',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AT': 'Austria',
    'AU': 'Australia',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia and Herzegovina',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BN': 'Brunei',
    'BO': 'Bolivia',
    'BR': 'Brazil',
    'BS': 'Bahamas',
    'BT': 'Bhutan',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CD': 'Democratic Republic of the Congo',
    'CF': 'Central African Republic',
    'CG': 'Congo',
    'CH': 'Switzerland',
    'CI': 'Cote d_Ivoire',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CV': 'Cabo Verde',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FM': 'Federated States of Micronesia',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GH': 'Ghana',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GW': 'Guinea Bissau',
    'GY': 'Guyana',
    'HK': 'Hong Kong',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IN': 'India',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'Saint Kitts and Nevis',
    'KP': 'Democratic People_s Republic of Korea',
    'KR': 'Korea',
    'KW': 'Kuwait',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LB': 'Lebanon',
    'LC': 'Saint Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova',
    'ME': 'Montenegro',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'MK': 'Macedonia',
    'ML': 'Mali',
    'MM': 'Myanmar',
    'MN': 'Mongolia',
    'MO': 'Macau',
    'MR': 'Mauritania',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PS': 'Palestine',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'SS': 'South Sudan',
    'ST': 'Sao Tome and Principe',
    'SV': 'El Salvador',
    'SY': 'Syria',
    'SZ': 'Swaziland',
    'TD': 'Chad',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TL': 'Timor-Leste',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TR': 'Turkey',
    'TT': 'Trinidad and Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TZ': 'Tanzania',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'US': 'USA',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VA': 'Holy See',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VN': 'Vietnam',
    'VU': 'Vanuatu',
    'WS': 'Samoa',
    'XA': 'XA',
    'XE': 'XE',
    'XK': 'Kosovo',
    'XM': 'XM',
    'XS': 'XS',
    'YE': 'Yemen',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
  };

  private getCountryName(countryCode: string): string {
      if (this.isoCountries.hasOwnProperty(countryCode)) {
          return this.isoCountries[countryCode];
      } else {
          return countryCode;
      }
  }
}
